name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the current repository
      - name: Checkout current repository code
        uses: actions/checkout@v2
        
      # Step 2: Check out to other repository
      - name: Checkout code from other repository
        uses: actions/checkout@v2
        with:
          repository: nagarajar/spring-boot-github-actions-demo
          ref: main
          path: spring-boot-github-actions-demo
          
      # Step 3: Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Build jar
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: spring-boot-github-actions-demo

      # Step 6: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/my-azure-app:latest .

      # Step 7: Login to Azure Container Registry (ACR)
      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # Step 8: Push Docker Image to ACR
      - name: Push Docker Image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-azure-app:latest
